using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class Constants
{
    public enum Destination
    {
        AFRICA = 1,
        AMERICA = 2,
        ASIA = 3,
        EUROPE = 4,
        OCEANIA = 5,
        AFRICA_AIRMAIL = 6,
        AMERICA_AIRMAIL = 7,
        ASIA_AIRMAIL = 8,
        EUROPE_AIRMAIL = 9,
        OCEANIA_AIRMAIL = 10,

        BELFAST = 11,
        CARDIFF = 12,
        EDINBURGH = 13,
        LONDON = 14,
        MANCHESTER = 15,
        BELFAST_SPECIAL = 16,
        CARDIFF_SPECIAL = 17,
        EDINBURGH_SPECIAL = 18,
        LONDON_SPECIAL = 19,
        MANCHESTER_SPECIAL = 20,

        ASHFORD_ROAD = 21,
        BRICK_ROAD = 22,
        COBB_LANE = 23,
        HARROW_ROAD = 24,
        KERFOOT_DRIVE = 25,
        LANSDOWNE_ROAD = 26,
        LEATHERHEAD_CLOSE = 27,
        ST_EDWARDS_ROAD = 28,
        WARPLE_WAY = 29,
        YORK_STREET = 30
    }

    public static readonly string[,] localDirectory = {
            { "1","Ashford Road" , "Mr", "Mustapha", "Alli", "BW1", "21"},
            { "2","Ashford Road" , "Ms", "Jacqueline", "Anderson", "BW1", "21" },
            { "4","Ashford Road" , "Mrs", "Evelyn", "Arnold", "BW1", "21" },
            { "4","Ashford Road" , "Mr", "Paul", "Arnold", "BW1", "21" },
            { "10A","Ashford Road" , "Mr", "Philip", "Ashworth", "BW1", "21" },
            { "10B","Ashford Road" , "Mrs", "Catherine", "Azevedo", "BW1", "21"},

            { "2","Brick Road" , "Mr", "Brian", "Benham", "BW2", "22" },
            { "4","Brick Road" , "Mrs", "Pamela", "Blair", "BW2", "22" },
            { "6","Brick Road" , "Mr", "Andrew", "Cheetham", "BW2", "22" },
            { "8","Brick Road" , "Mr", "Michael", "Christie", "BW2", "22" },
            { "10","Brick Road" , "Mr", "Alan", "Conboy", "BW2", "22" },

            { "2","Cobb Lane" , "Mrs", "Shirley", "Coy", "BW3", "23" },
            { "2","Cobb Lane" , "Mr", "Richard", "Coy", "BW3", "23" },
            { "7","Cobb Lane" , "Mr", "Braham", "Datt", "BW3", "23"},
            { "8","Cobb Lane" , "Mr", "Terence", "Day", "BW3", "23"},
            { "10","Cobb Lane" , "Ms", "Julie", "Easton", "BW3", "23" },

            { "2","Harrow Road" , "Mr", "Henry", "Ellis", "BW4", "24" },
            { "7","Harrow Road" , "Mr", "Christopher", "Evans", "BW4", "24" },
            { "11","Harrow Road" , "Mr", "Thomas", "Fickling", "BW4", "24" },
            { "14","Harrow Road" , "Mr", "Michael", "Foreman", "BW4", "24" },
            { "23","Harrow Road" , "Mrs", "Barbara", "Harris", "BW4", "24" },

            { "1","Kerfoot Drive" , "Mr", "Calbert", "Ellis", "BW5", "25" },
            { "2","Kerfoot Drive" , "Mrs", "Jane", "Ellis", "BW5", "25" },
            { "3","Kerfoot Drive" , "Ms", "Valerie", "Johnston", "BW5", "25" },
            { "4","Kerfoot Drive" , "Mr", "Stephen", "Jones", "BW5", "25" },
            { "5","Kerfoot Drive" , "Mrs", "Olga", "Lange", "BW5", "25" },

            { "1","Lansdowne Road" , "Mr", "Phillip", "Lowe", "BW6", "26" },
            { "4","Lansdowne Road" , "Mr", "Steven", "MacKinnon", "BW6", "26" },
            { "5","Lansdowne Road" , "Mr", "David", "Madge", "BW6", "26"},
            { "11","Lansdowne Road" , "Mr", "Vaqas", "Mahmood", "BW6", "26" },
            { "12","Lansdowne Road" , "Ms", "Angela", "McMullen", "BW6", "26" },

            { "1","Leatherhead Close" , "Mr", "Sylvia", "Moffat", "BW7", "27" },
            { "4","Leatherhead Close" , "Mrs", "Jennifer", "Mundy", "BW7", "27" },
            { "5","Leatherhead Close" , "Mr", "Justin", "Nicholas", "BW7", "27" },
            { "17","Leatherhead Close" , "Mr", "Terence", "Oram", "BW7" , "27"},
            { "26","Leatherhead Close" , "Mr", "Jayesh", "Patel", "BW7", "27" },

            { "3","St Edwards Road" , "Mr", "Geoffrey", "Townsend-Philipps", "BW8", "28" },
            { "3","St Edwards Road" , "Mr", "Michael", "Townsend-Philipps", "BW8", "28" },
            { "4","St Edwards Road" , "Mr", "Ray", "Shepherd", "BW8", "28"},
            { "9","St Edwards Road" , "Mr", "Joyce", "Tull", "BW8", "28"},
            { "13","St Edwards Road" , "Mr", "Sarah", "Wallis", "BW8" , "28"},

            { "3","Warple Way" , "Mr", "Carol", "Armstrong", "BW9", "29" },
            { "7","Warple Way" , "Mr", "Stuart", "Atkinson", "BW9", "29" },
            { "11","Warple Way" , "Mr", "Alan", "Banham", "BW9", "29" },
            { "14","Warple Way" , "Mr", "Jason", "Bedward", "BW9", "29"  },
            { "24","Warple Way" , "Mr", "Osaro", "Benson", "BW9" , "29" },

            { "3","York Street" , "Mr", "Alfred", "Berry", "BW10", "30"  },
            { "4","York Street" , "Mr", "Leon", "Bott", "BW10", "30"},
            { "6","York Street" , "Mr", "Julie", "Caffrey", "BW10", "30"},
            { "13","York Street" , "Mr", "Peter", "Coombes", "BW10", "30" },
            { "19","York Street" , "Mr", "Elizabeth", "Gooding", "BW10", "30" }

    };

    public static readonly int nationalDirectoryCount = 5;
    public static readonly string[,] nationalDirectory = {
        { "Belfast", "B", "11" },
        { "Cardiff","C","12"},
        { "Edinburgh","E","13"},
        { "London","L","14"},
        { "Manchester","M","15"}};

    public static readonly int internationalDirectoryCount = 45;
    public static readonly string[,] internationalDirectory = {
        {"Egypt", "101", "Africa" , "1"},
        {"Nigeria", "102", "Africa" , "1"},
        {"South Africa", "103", "Africa" , "1"},
        {"Ghana", "104", "Africa" , "1"},
        {"Kenya", "105", "Africa" , "1"},
        {"Saudi Arabia", "106", "Africa" , "1"},
        {"Angola", "107", "Africa" , "1"},
        {"Liberia", "108", "Africa" , "1"},
        {"Guinea Bissau", "109", "Africa" , "1"},

        {"Canada", "201", "Americas" , "2"},
        {"USA", "202", "Americas" , "2"},
        {"Mexico", "203", "Americas" , "2"},
        {"Brazil", "204", "Americas" , "2"},
        {"Peru", "205", "Americas" , "2"},
        {"Argentina", "206", "Americas" , "2"},
        {"Chile", "207", "Americas" , "2"},
        {"Puerto Rico", "208", "Americas" , "2"},
        {"Uruguay", "209", "Americas" , "2"},

        {"China", "301", "Asia" , "3"},
        {"India", "302", "Asia" , "3"},
        {"Japan", "303", "Asia" , "3"},
        {"South Korea", "304", "Asia" , "3"},
        {"Kyrgyzstan", "305", "Asia" , "3"},
        {"Malaysia", "306", "Asia" , "3"},
        {"Vietnam", "307", "Asia" , "3"},
        {"Turkmenistan", "308", "Asia" , "3"},
        {"Thailand", "309", "Asia" , "3"},

        {"France", "401", "Europe" , "4"},
        {"Germany", "402", "Europe" , "4"},
        {"Spain", "403", "Europe" , "4"},
        {"Greece", "404", "Europe" , "4"},
        {"Turkey", "405", "Europe" , "4"},
        {"Ukraine", "406", "Europe" , "4"},
        {"Norway", "407", "Europe" , "4"},
        {"Iceland", "408", "Europe" , "4"},
        {"Monaco", "409", "Europe" , "4"},

        {"Australia", "501", "Oceania" , "5"},
        {"New Zealand", "502", "Oceania" , "5"},
        {"Papua New Guinea", "503", "Oceania" , "5"},
        {"Fiji", "504", "Oceania" , "5"},
        {"Samoa", "505", "Oceania" , "5"},
        {"Nauru", "506", "Oceania" , "5"},
        {"Kiribati", "507", "Oceania" , "5"},
        {"Solomon Islands", "508", "Oceania" , "5"},
        {"Tonga", "509", "Oceania" , "5"} };




    public static readonly string[] names = {
        "Leroy Alvarado",
"Amaya Barber",
"Izaak Friedman",
"Beau Hooper",
"Szymon Gallagher",
"Isobel Reyes",
"Annabella Short",
"Jazmin Abbott",
"Marco Murray",
"Keane Melendez",
"Stephen Huffman",
"Blake Kaufman",
"Elin Guzman",
"Lauren Jones",
"Constance Copeland",
"Hallie Slater",
"Wilson Luna",
"Casper Petersen",
"Ciara Willis",
"Frederick Nichols",
"Marina Rangel",
"Kimberly Espinoza",
"Alannah Hansen",
"Jana Odling",
"Kane Rich",
"Sumayyah Escobar",
"Cindy Cruz",
"Daniela Ward",
"Richie Jefferson",
"Cassandra English",
"Elaine Sykes",
"Josephine Hendrix",
"Ishaq Beard",
"Neo Robertson",
"Linda Poole",
"Sofia Blankenship",
"Declan Higgins",
"Sallie Douglas",
"Demi-Leigh Lynn",
"Adriana Lyons",
"Carmen Griffith",
"Joan Ryan",
"Scott Anthony",
"Xander Gardner",
"Ana Mueller",
"Dawud Rios",
"Samson Brady",
"Maia Zuniga",
"Cassie Sampson",
"Fleur Beasley",
"Freya Evans",
"Luc Crawford",
"Kiera Cuevas",
"Mollie Huff",
"Bessie Hamilton",
"Kain Fowler",
"Nevaeh Reeves",
"Wilma Barton",
"Aleeza Mcknight",
"Kate Payne",
"Brittney Deleon",
"Cora Bell",
"Annabelle Ferguson",
"Lillian Summers",
"Arran Carr",
"Elise Meza",
"Sylvie Gregory",
"Jorge Garcia",
"Carys Christian",
"Alexandre Spencer",
"Johnathan Levine",
"Donna Carlson",
"Spencer Barry",
"Erika Wyatt",
"Salma Macdonald",
"Rhiannon Schwartz",
"Naima Chavez",
"Haaris Boyer",
"Honey Graham",
"Hattie Tapia",
"Lara Matthews",
"Dillan Hendricks",
"Ismail Hartman",
"Ayub Norman",
"Cynthia Vazquez",
"Jerry Howe",
"Ehsan Yoder",
"Lyndon Carver",
"Lyra Everett",
"Andre Ortega",
"Michael Lucero",
"Miguel Bird",
"Regan Merrill",
"Pablo Walter",
"Molly Case",
"Mia Tyler",
"Jacqueline Merritt",
"Ted Guerra",
"Usman Solomon",
"Paula Mathews",
"Lilly Mendez",
"Ruairi Baird",
"Naomi Burch",
"Inayah Wells",
"Hamish Thompson",
"Jordanne Lester",
"Ieuan Sanchez",
"Wojciech Dorsey",
"Melissa Mccann",
"Yasin Stewart",
"Susannah Odom",
"Iona Goodwin",
"Mustafa Terry",
"Amir Castro",
"Yusuf Andersen",
"Katerina Parker",
"Bertha Hayes",
"Laiba Houston",
"Marie Hood",
"Amira Garrett",
"Tilly Cantrell",
"Safaa Alexander",
"Archibald Gentry",
"Lucia Frank",
"Gabriella Caldwell",
"Isobella Wallace",
"Sharon Hansen",
"Arman Rangel",
"Mathilda Hobbs",
"Jesse Meza",
"Bronwyn O'Doherty",
"Yasmine Silva",
"Renee Dean",
"Hugh Williams",
"Damian Morales",
"Ashley Hanson",
"Bilal Owen",
"Sufyaan Atkins",
"Ethan Patel",
"Stefan Gibbs",
"Rupert Golden",
"Tammy Ibarra",
"Bethan Leblanc",
"Delilah Bray",
"Alistair Fry",
"Nate Nichols",
"Brodie Sykes",
"Sapphire England",
"Cohen Rivers",
"Howard Morrison",
"Khadijah Carter",
"Talia Goodman",
"Ollie Cantu",
"Fabian Sweeney",
"Kobe Shelton",
"Arianna Clark",
"Susie Best",
"Stephanie Nelson",
"Jenna Booker",
"Alastair Hebert",
"Richard Lambert",
"Isobel Cruz",
"Chiara Haney",
"Stephen Petersen",
"Drew Osborne",
"Maisey Mejia",
"Sarah Jennings",
"Tyrese Hampton",
"Henrietta Mccall",
"Jaden Norton",
"Sam Atkinson",
"Matilda Schneider",
"Larissa Bell",
"Miguel Figueroa",
"Faizan Escobar",
"Ellena Pham",
"Carter Huff",
"Lena Murray",
"Kaylum Villegas",
"Bertie Pace",
"Stacey Hahn",
"Nina Alvarado",
"Ebony Benson",
"Maxwell Pugh",
"Nikhil Christensen",
"Eric Brown",
"Faye Weaver",
"Nettie Chang",
"Lina Macdonald",
"Isha Doherty",
"Zoe Todd",
"Gideon Walter",
"Kristina Mullen",
"Iqra Calderon",
"Russell Robertson",
"Tariq Holden",
"Tom Mckee",
"Samir Bauer",
"Kendra Lee"};

    public static readonly string[] streetNames = {
    "High Street",
"Station Road",
"Main Street",
"Park Road",
"Church Road",
"Church Street",
"London Road",
"Victoria Road",
"Green Lane",
"Manor Road",
"Church Lane",
"Park Avenue",
"The Avenue",
"The Crescent",
"Queens Road",
"New Road",
"Grange Road",
"Kings Road",
"Kingsway",
"Windsor Road",
"Highfield Road",
"Mill Lane",
"Alexander Road",
"York Road",
"St.John’s Road",
"Main Road",
"Broadway",
"King Street",
"The Green",
"Springfield Road",
"George Street",
"Park Lane",
"Victoria Street",
"Albert Road",
"Queensway",
"New Street",
"Queen Street",
"West Street",
"North Street",
"Manchester Road",
"The Grove",
"Richmond Road",
"Grove Road",
"South Street",
"School Lane",
"The Drive",
"North Road",
"Stanley Road",
"Chester Road",
"Mill Road" };



    public static readonly string[] goodJob = {
    "Excellent work.\r\n Really got the hang of it I see",
    "Jolly good. Keep up the good work",
    "Good good",
    "Good to see. "
    };

    public static readonly string[] refManuals =
    {
    "The Post Office reference manuals are a junior sorters best friend",
    "The reference manuals hold a wealth of information",
    "Check the reference books if you have trouble"
    };

    public static readonly string[] endDayFlavour =
    {
    "Don't forget\r\n bank holiday Monday.",
    "Jenny has brought cake.\r\nIt's in the kitchen",
    "No on really cares what these reports say",
    "Have you seen my mug\r\n It's the Bottomswoth FC one",
    "Rose annd Crown after work :)",
    "Donuts\r\n in the ktchen",
    "The smell in the hallway is being investigated",
    "Expense reminder\r\n In tomorow if you have any"
    };

    public static readonly string[] postcardFlavour =
    {
        "Wish you were here!",
        "Having a great time",
        "This place is awsome",
        "Having fun but I miss you all"
    };

    public static readonly string spost1 = "Hi Mum,\r\nYou would not believe how hot it is here. So good to get away from the rain. Our hostel is right on the beach. And there’s a floating bar. We met a couple of girls from France and we are all going on the eco turn tomorrow\n\rHope you are keeping good\n\rLove Masie";

    public static readonly string spost2 = "Hey Mum\r\nHaving a blast here. The night market was amazing. Bought some cute earrings and we had the best street food. Jenny got a bit sick, bit of dodgy food. But she’s better now and we are going up the cable car tomorrow.\r\n Love Masie";

    public static readonly string spost3 = "Hi Mum,\r\nIt’s weird being back in Europe. Can’t believe the trip is almost over. Still so much to see. Harry has been showing us around the city. He’s lived here for a bit and he knows the stuff off the tourist trail.\r\nSee you soon\r\nLove Masie";


}
